version: "3.9"

services:
  frontend:
    container_name: load-nft-frontend
    image: load-nft/frontend
    build:
      context: ./
      dockerfile: ./frontend.Dockerfile
      args:
        REMOTE_REPOSITORY: git@github.com:dzubape/vps-build-user.git
        KEY_FILENAME: loadsite_rsa
    ports:
      - 10080:80
      - 10443:443
    restart: always
  # backend:
  #   container_name: load-nft-backend
  #   image: load-nft/backend
  #   build:
  #     context: ./
  #     dockerfile: ./backend.Dockerfile
  #   ports:
  #     - 11080:80
  #     - 11443:443
  #   restart: always